stages:          # List of stages for jobs and their order of execution
  - build-images
  - frontend
  - backend
  - deploy


build-images:
  stage: build-images
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --file frontend/Dockerfile -t registry.gitlab.com/software-engineering8932241/job-hunting:frontend_image_$CI_COMMIT_SHORT_SHA .
    - docker build --file backend/Dockerfile -t registry.gitlab.com/software-engineering8932241/job-hunting:backend_image_$CI_COMMIT_SHORT_SHA .
    - docker push registry.gitlab.com/software-engineering8932241/job-hunting:frontend_image_$CI_COMMIT_SHORT_SHA
    - docker push registry.gitlab.com/software-engineering8932241/job-hunting:backend_image_$CI_COMMIT_SHORT_SHA

frontend:
  stage: frontend
  image: registry.gitlab.com/software-engineering8932241/job-hunting:frontend_image_$CI_COMMIT_SHORT_SHA
  script:
    - echo "Frontend Image"


backend:
  stage: backend
  image: registry.gitlab.com/software-engineering8932241/job-hunting:backend_image_$CI_COMMIT_SHORT_SHA
  script:
    - echo "Backend Image"


deploy-prod:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY"
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H 35.221.223.176 > ~/.ssh/known_hosts
  script:
    - ssh group4@35.221.223.176
    - export IMAGE=registry.gitlab.com/software-engineering8932241/job-hunting:frontend_image_$CI_COMMIT_SHORT_SHA
    - docker pull $IMAGE
    - docker run -d -t frontend $IMAGE
    - export IMAGE=registry.gitlab.com/software-engineering8932241/job-hunting:backend_image_$CI_COMMIT_SHORT_SHA
    - docker pull $IMAGE
    - docker run -d -t backend $IMAGE
    - exit
  after_script:
    - rm -rf ~/.ssh
