stages:          # List of stages for jobs and their order of execution
  - build
  - frontend
  - backend
  - deploy


build-job:
  stage: build
  image: python:latest
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - python test.py

frontend-job:
  stage: frontend
  # image: openjdk:8-jdk-alpine
  script:
    - echo "Frontend Image"


backend-job:
  stage: backend
  image: openjdk:8-jdk-alpine
  script:
    - echo "Backend Image"


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
