stages:          # List of stages for jobs and their order of execution
  - build-images
  - frontend
  - backend
  - deploy


build-images:
  stage: build-images
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --file frontend/Dockerfile -t registry.gitlab.com/software-engineering8932241/job-hunting:frontend_image .
    - docker build --file backend/Dockerfile -t registry.gitlab.com/software-engineering8932241/job-hunting:backend_image .
    - docker push registry.gitlab.com/software-engineering8932241/job-hunting:frontend_image
    - docker push registry.gitlab.com/software-engineering8932241/job-hunting:backend_image

frontend:
  stage: frontend
  image: registry.gitlab.com/software-engineering8932241/job-hunting:frontend_image
  script:
    - echo "Frontend Image"


backend:
  stage: backend
  image: registry.gitlab.com/software-engineering8932241/job-hunting:backend_image
  script:
    - echo "Backend Image"


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
